export const productList = [
  { id: 1,
    name: 'Good Bye Sunshine',
    color: '#e3771c',
    url: 'goodByeSunshine',
    subName: 'Facial Wash',
    skinType: ['oily','problematic'],
    productType: ['cleanser'],
    description:
    'Waking up to greasy skin and new pimples every morning? if you answered yes, then you are looking at the right product. Our Goodbye Sunshine Facial Wash is exactly what you need to wash away oiliness and impurities from your face and kickstart',
    loveList: [
      "Salicylic Acid’s natural astringent function helps control excess oil",
      'Papaya and Pineapple Enzymes work together to gently remove dead skin cells',
      'Lime & Juniper Essential Oils deeply cleanse the skin and kill off surface bacteria to prevent blemishes'
    ],
    directions: 'Apply a small amount to the face, neck and décolletage, then gently massage into the skin, avoiding eye area. Add a little water to create a foaming action, and then remove with warm water or face cloth. Use morning and night.',
    ingredients: 'Purified Water, Lauryl glucoside (Coconut & Sugar derived), Glycerin*, Asimina Triloba (Papaya) extract*, Cocamido Propyl Betaine (Coconut derived), Ananas Sativus (Pineapple fruit extract), Salix Alba (White Willow bark), Glycyrrhiza Glabra (Liquorice) root extract*, Syzygium Leuhmanii (Lilli Pilli) fruit extract*, Citric acid, Citrus Sinensis (Orange) essential oil, Citrus Aurantifolia (Lime) essential oil, Citrus bergamia (Bergamot) essential oil, Juniperus Deppeana (Juniper) essential oil, Tocopherol (Vitamin E), Hydroxymethylglycinate (Glycerin derived)',
    size: "200ml",
    price: 30,
    img: "/images/products/Good-Bye-Sunshine-Facial-Wash_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 2,
    name: 'All Under Control',
    color: '#947cb0',
    url: 'allUnderControl',
    subName: 'Toning Mist',
    skinType: ['oily','problematic'],
    productType: ['toning mist'],
    description:
    'Just a few spritzes of the All Under Control Toning Mist and your skin will instantly benefit from its amazing anti-inflammatory and hydrating properties. You can spritz this all over you face during the day for a quick refreshing pick me up.',
    loveList: [
      'Aloe Vera cools down and hydrates the skin',
      'Natural fruit enzymes dissolve dead skin cells',
      'Lime, Sweet Orange and Orange Blossom Essential Oils kill bacteria and prevent breakouts',
      'Alcohol Free'
    ],
    directions: 'Hold toning mist approx. 25cm above your face with your eyes closed and spray 1-2 times, alternatively you can apply to cotton pads and gently wipe the skin. Allow to dry before applying a moisturiser. Use daily.',
    ingredients: 'Aloe Barbadensis (Aloe Vera) juice*, Glycerin*, Asimina Triloba (Papaya) extract*, Ananas Sativus (Pineapple) fruit extract, Pyrus Malus (Apple) extract*, Solubilizer (Coconut & Almond derived), Citrus Sinensis (Orange) essential oil, Citrus Aurantifolia (Lime) essential oil, Citrus Bergamia (Bergamot) essential oil, Juniperus Deppeana (Juniper) essential oil, Tocopherol (Vitamin E), Leuconostoc (Radish root) ferment filtrate, Potassium Sorbate (Salt derived)',
    size: "150ml",
    price: 30,
    img: "/images/products/All-Under-Control-Toning-Mist_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 3,
    name: 'Lemon Candy',
    color: '#fbef37',
    url: 'lemonCandy',
    subName: 'Active Peel',
    skinType: ['oily', 'problematic', 'normal'],
    productType: ['exfoliant'],
    description:
    "You already know that gentle exfoliation is a crucial step in the healing process of acne prone and congested skin. That's why we created our Lemon Candy Active Peel. This is the most gentle yet effective natural resurfacing peel you will ever come across.",
    loveList: [
      '15% blend of fruit enzymes team up to "unglue" dead skin cells from the top layer of your skin',
      'Pomegranate and Liquorice minimise the appearance of dark spots',
      'Aloe Vera helps improve skin texture',
      'No inflammation or irritation after use'
    ],
     directions: 'Gently apply to the face and décolletage, avoiding eye area. Leave on for approximately 2-5 minutes, before removing with water. A slight tingling is normal, if burning sensation occurs please remove immediately.',
    ingredients: 'Aloe Barbadensis (Aloe Vera) gel*, Aloe Barbadensis (Aloe Vera) extract*, Glycerin*, Asimina Triloba (Papaya)*, Punica Granatum Pericarp (Pomegranate) extract, Santalum Acuminatum (Quandong) extract*, Ananas Sativus fruit (Pineapple)extract, Salix Alba (White Willow bark) extract, Teriminalia Ferdinandiana (Kakadu Plum) extract*, Glycyrrhiza Glabra (Liquorice) root extract*, Camellia Sinensis (Green Tea) extract*, Xanthan gum, Citric Acid, Citrus Sinensis (Orange) essential oil, Citrus Limon peel (Lemon) essential oil*',
    size: '60ml',
    price: 30,
    img: "/images/products/Lemon-Candy-Active-Peel_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 4,
    name: 'Seal the Deal',
    color: '#7b2c88',
    url: 'sealTheDeal',
    subName: 'Serum',
    skinType: ['oily', 'problematic'],
    productType: ['serum'],
    description:
    "Did you know that even oily skin can be dehydrated? It is actually quite common for skin to produce way too much sebum to compensate for the lack of water. By integrating our Seal The Deal Serum into your routine you'll restore your skin's hydration levels and boost the performance of the rest of your skin care products.",
    loveList: [
      'It glides on like silk and absorbs almost immediately to lock in moisture',
      'Liquorice, White Willow Bark and Papaya Extract will help lighten up dark spots',
      'Aloe Vera helps improve skin texture',
      'Lovely tropical scent of Lime, Orange and Bergamot Essential Oils'
    ],
     directions: 'Apply a small amount to the face, neck and décolletage and massage in using gentle upward strokes. For best results apply a moisturiser over the top of your serum. Avoid eye area. Use morning and night.',
    ingredients: 'Aloe Barbadensis (Aloe Vera) gel*, Aloe Barbadensis (Aloe Vera) extract*, Glycerin*, Glycyrrhiza Glabra (Liquorice) root extract, Asimina Triloba (Papaya)*, Niacinamide (Vitamin B3), Salix Alba (White Willow Bark), Camellia Sinensis (Green Tea)*, Xanthan Gum, Citrus Sinensis (Orange) essential oil, Citrus Aurantifolia (Lime) essential oil, Citrus Bergamia (Bergamot) essential oil, Juniperus Deppeana (Juniper) essential oil, Citrus Limon peel (Lemon) essential oil*, Tocopherol (Vitamin E)',
    size: '30ml',
    price: 30,
    img: "/images/products/Seal-The-Deal-Gel-Serum_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 5,
    name: 'The Porefect',
    color: '#7eae96',
    url: 'thePorefect',
    subName: 'Day Cream',
    skinType: ['oily', 'problematic'],
    productType: ['moisturiser'],
    description:
    "No great skin care routine is complete without a great moisturiser. The name says it all: The Porefect Day cream is a light lotion that absorbs instantly leaving no greasy residue. It will quickly minimise the appearance of pores and prevent nasty blackheads and other blemishes to appear.",
    loveList: [
      'Salicylic acid works throughout the day to dissolve excess sebum build up',
      'Papaya and Pineapple enzymes allow pores to remain clean and unclogged',
      'Mattifies skin and makes blemishes less visible',
      'Can apply mineral make-up straight after, no primer needed'
    ],
     directions: 'Apply a small amount to the face, neck and décolletage and massage in using gentle upward strokes. Avoid eye area. Use morning and night.',
    ingredients: 'Purified Water, Glycerin*, Isopropyl Myristate, Prunus Amygdalus Dulcis (Sweet Almond), Cetearyl Alcohol (Coconut derived), Glyceryl Stearate (Vegetable derived), Asimina Triloba (Papaya)*, Ananas Sativus (Pineapple) fruit extract, Glycyrrhiza Glabra (Liquorice) root extract*, Salix Alba (White Willow bark), Sodium Stearate (Salt derived), Camellia Sinensis (Green Tea)*, Teriminalia Ferdinandiana (Kakadu Plum)*, Sodium Cetyl Phosphate, Tocopherol (Vitamin E), Santalum Acuminatum (Quandong)*, Citrus Sinensis (Orange) essential oil, Citrus Aurantifolia (Lime) essential oil, Citrus Bergamia (Bergamot) essential oil, Juniperus Deppeana (Juniper) essential oil, Hydroxymethylglycinate (Glycerin derived)',
    size: '60ml',
    price: 30,
    img: "/images/products/The-Porefect-Day-Cream_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 6,
    name: 'Cool As Cucumber',
    color: '#7dba6a',
    url: 'coolAsCucumber',
    subName: 'Milk Cleanser',
    skinType: ['sensitive', 'dry'],
    productType: ['cleanser'],
    description:
    "Do you struggle to find a natural everyday cleanser for your sensitive skin? Something that won't give you any adverse reaction and won't leave your skin feeling tight? If this sounds like you, give our Cool As Cucumber Milk Cleanser a try. It will calm your hot, irritated skin without drying it out. Plus, it will leave your skin super soft and smelling amazing!",
    loveList: [
      'Cucumber cools irritation and comforts sensitive skin',
      'Desert Lime helps brighten skin complexion',
      'Perennial herbs purify the skin and protect it from environmental stress',
      'Gently removes any trace of mineral make up'
    ],
     directions: 'Apply a small amount to the face, neck and décolletage, then gently massage into skin, avoiding eye area. Remove with warm water or face cloth. Use morning and night',
    ingredients: 'Aloe Barbadensis (Aloe Vera) leaf juice, Rosa Eglanteria (Rose Hip) oil*, Cocoglucoside (Coconut & Sugar derived), Stearic Acid (Vegetable derived), Glyceryl Stearate (Vegetable derived), Glycerin*, Cucumis Sativus (Cucumber) extract, Cucumis Sativus (Cucumber) seed oil, Citrus Glauca (Desert Lime)*, Xanthum gum, Cetearyl alcohol (Coconut derived), Origanum Vulgare (Oregano) oil, Thymus Vulgaris (Thyme) extract, Olea Europeia (Olive) leaf extract, Rosmarinus Officinalis (Rosemary) leaf extract, Lavandula Angustifolia (Lavender) flower extract, Citrus Sinensis (Orange) essential oil*, Cedrus Atlantica (Cedar Wood Atlas) essential oil*, Cananga Odorata (Ylang Ylang) essential oil*, Citrus Aurantifolia (Lime) essential oil*, Citrus Aurantium Amara (Neroli) essential oil*',
    size: '200ml',
    price: 30,
    img: "/images/products/Cool-As-Cucumber-Milk-Cleanser_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 7,
    name: 'Quick Fix',
    color: '#ebc644',
    url: 'quickFix',
    subName: 'Toning Mist',
    skinType: ['sensitive'],
    productType: ['toning mist'],
    description:
    "Just a spray of the Quick Fix Toning Mist after the using our cleanser and throughout the day will deliver an immediate much needed moisture boost to you skin and prevent any tightness and itchiness. This natural toner will soothe and refresh even the most sensitive skin type while keeping it hydrated.",
    loveList: [
      'Aloe Vera cools and hydrates hot, irritated skin',
      'Wild harvested Quandong dissolves dead skin cells and prevent blemishes',
      'Vitamin C helps brighten skin complexion',
      'Alcohol free'
    ],
     directions: 'Hold toning mist approx. 25cm above your face with your eyes closed and spray 1-2 times, alternatively you can apply to cotton pads and gently wipe the skin. Allow to dry before applying a moisturiser. Use daily.',
    ingredients: 'Aloe Barbadensis (Aloe Vera) juice*, Glycerin*, Asimina Triloba (Papaya)*, Santalum Acuminatum (Quandong)*, Teriminalia Ferdinandiana (Kakadu Plum)*, L-Ascorbic Acid (Vitamin C), Solubilizer (Coconut & Almond derived), Cymbopogon Flexuosus (Lemongrass) essential oil*, Citrus Aurantifolia (Lime) essential oil, Citrus Bergamia (Bergamot) essential oil*, Tocopherol (Vitamin E), Leuconostoc (Radish Root) ferment filtrate, Potassium Sorbate (Salt derived)',
    size: '150ml',
    price: 30,
    img: "/images/products/Quick-Fix-Toning-Mist_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 8,
    name: 'No Handyman Needed',
    color: '#ac1684',
    url: 'noHandyMan',
    subName: 'Day Cream',
    skinType: ['sensitive'],
    productType: ['moisturiser'],
    description:
    "Taking care of your sensitive skin and giving it all the nutrients it needs to self-repair has never been easier. That's right, because our No Handyman Needed Day Cream is jam-packed full of calming, nourishing and restoring natural ingredients. It will quickly reduce redness and inflammation for a healthier, naturally vibrant skin.",
    loveList: [
      "Rose hip oil boosts the skin's natural healing process",
      'Green tea prevents cell damage and improves the appearance of dark spots',
      'Hyaluronic Acid and Finger Lime provide intense hydration all day long',
      'Light silky consistency that absorbs immediately'
    ],
     directions: 'Apply a small amount to the face, neck and décolletage and massage in using gentle upward strokes. Avoid eye area. Use morning and night.',
    ingredients: 'Aloe Barbadensis (Aloe Vera) leaf juice, Rosa Eglanteria (Rose Hip) oil*, Coco-Glucoside, Stearic Acid (vegetable derived), Glyceryl Stearate (vegetable derived), Glycerin*, Cucumis Sativus (Cucumber) extract, Citrus Glauca (Desert Lime)*, Xanthum Gum, Cetearyl Alcohol (Coconut derived), Sodium Hyaluronate (Hyaluronic Acid), Camellia Sinensis (Green Tea)*, Teriminalia Origanum Vulgare (Oregano) oil, Thymus Vulgaris (Thyme) extract, Olea Europeia (Olive) Leaf extract, Rosmarinus Officinalis (Rosemary) Leaf extract, Lavandula Angustifolia (Lavender) flower extract, Citrus Sinensis (Blood Orange) essential oil, Cananga Odorata (Ylang Ylang) essential oil*, Rosa Damascena (Rose) essential oil*',
    size: '60ml',
    price: 30,
    img: "/images/products/No-Handyman-Needed-Day-Cream_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 9,
    name: 'Green Cocktail',
    color: '#55924d',
    url: 'greenCocktail',
    subName: 'Foam Cleanser',
    skinType: ['dry', 'normal'],
    productType: ['cleanser'],
    description:
    "Our gentle Green Cocktail Foam Cleanser is ideal for the busy urban girl, always running around town. It deeply cleanses and protects the skin against free radical damage. It is packed full of powerful greens to brighten up the skin and maintain it healthy and elastic.",
    loveList: [
      'Wheatgrass is high in antioxidants and protects skin against environmental toxins',
      'Green tea helps neutralise free radicals and improves skin tone',
      'Alfalfa Grass contains Vitamin A and enzymes, essentials for natural glowing skin',
      'Parsley is high in Vitamin C and helps with the prevention of blemishes',
      'Gently removes any trace of mineral make up',
    ],
     directions: 'Apply a small amount to the face, neck and décolletage, then gently massage into the skin, avoiding eye area. Add a little water to create a foaming action, and then remove with warm water or face cloth. Use morning and night.',
    ingredients: 'Purified Water, Lauryl Glucoside (Coconut & Sugar derived), Glycerin*, Cocamido Propyl Betaine (Coconut derived), Triticum Aestivum (Wheatgrass) leaf extract, Camellia Sinensis (Green Tea) leaf extract, Citric Acid, Chlorophyll (Alfalfa Grass), Citrus Sinensis (Orange) essential oil, Carum Petroselinum (Parsley seed) herb extract, Myroxylon Pereirae (Peru Balsam) oil, Leptospermum Petersonii ( Lemon Tea Tree) oil, Citrus Aurantium Var Amara (Petitgrain) oil, Tocopherol (Vitamin E), Hydroxymethylglycinate (Glycerin derived)',
    size: '200ml',
    price: 30,
    img: "/images/products/Green-Cocktail-Foam-Cleanser_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 10,
    name: 'Berry Fresh',
    color: '#615a9d',
    url: 'berryFresh',
    subName: 'Toning Mist',
    skinType: ['dry', 'normal'],
    productType: ['toning mist'],
    description:
    "Your skin will literally celebrate after every use of our Berry Fresh Toning Mist. This zesty toner contains three different superfoods rich in anti-oxidants, vitamins and nutrients to feed, protect and refresh your skin!",
    loveList: [
      'Goji Berries protect skin from environmental and personal stress',
      'Blueberries brighten up the complexion of dull skin and help minimise the appearence of sun spots',
      'Bilberries hydrate, refresh and maintain skin looking healthy and youthful',
      'Perfect as a makeup freshening spritz throughout the day'
    ],
    directions: 'Hold toning mist approx. 25cm above your face with your eyes closed and spray 1-2 times, alternatively you can apply to cotton pads and gently wipe the skin. Allow to dry before applying a moisturiser. Use daily.',
    ingredients: 'Aloe Barbadensis (Aloe Vera) juice*, Glycerin*, Lycium Chinense fruit extract (Goji Berry), Vaccinium Uliginosum (Blueberry) berry extract, Vaccinium Myrtillus (Bilberry) fruit extract, Solubilizer (Coconut & Almond derived), Citrus Sinensis (Orange) essential oil, Citrus Limon (Lemon) peel oil, Pelargonium Graveolens (Geranium Bourbon) essential oil, Citrus Paradisi (White Grapefruit) peel oil, Jasminum Sambac (Jasmine), Tocopherol (Vitamin E), Leuconostoc (Radish root) ferment filtrate, Potassium Sorbate (Salt derived)',
    size: '150ml',
    price: 30,
    img: "/images/products/Berry-Fresh-Toning-Mist_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 11,
    name: 'All About Moisture',
    color: '#5689c8',
    url: 'allAboutMoisture',
    subName: 'Hyaluronic Serum',
    skinType: ['dry', 'normal', 'sensitive'],
    productType: ['serum'],
    description:
    "Say goodbye to itchy dry patches with our All About Moisture Hyaluronic Serum made from 100% pure hyaluronic acid. If you suffer from dry or dehydrated skin, this product is definitely a must-have for you. Your skin will instantly soak up this wonderful light serum and feel smooth, fresh and hydrated straight after application.",
    loveList: [
      'Pure hyaluronic acid has been proven scientifically to hold up to 1000 times its weight in water and will help to instantly hydrate and plump the skin'
    ],
    directions: 'Apply a small amount to the face, neck and décolletage and massage in using gentle upward strokes. For best results add a few drops of water into your serum before applying and then finish off with a moisturiser. Use morning and night.',
    ingredients: 'Purified Water, Hyaluronic Acid (Vegan), Leuconostoc (Radish Root) ferment filtrate*',
    size: '30ml',
    price: 30,
    img: "/images/products/All-About-Moisture-Hyaluronic-Serum_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 12,
    name: 'Acai Bowl on my face',
    color: '#774260',
    url: 'acaiBowl',
    subName: 'Day Cream',
    skinType: ['dry', 'normal'],
    productType: ['moisturiser'],
    description:
    "Here's another great product to complete the morning routine for the busy urban girl. Acai Bowl On My Face Day Cream nourishes the skin while feeling light and fresh. It is packed with anti-oxidant superfoods, used to fight free radicals and protect the skin from environmental damage. You will never get enough of this!",
    loveList: [
      'Lemon Myrtle has powerful anti-oxidant and lightening properties',
      'Mangosteen is rich in skin-loving vitamins such as Vitamin C, which helps increase collagen production and brighten the skins complexion',
      'Acai berries promote healthy skin by nourishing it and improving its elasticity',
      'Beautifully scented with Rose Geranium and White Grapefruit'
    ],
    directions: 'Apply a small amount to the face, neck and décolletage and massage in using gentle upward strokes. Avoid eye area. Use morning and night.',
    ingredients: 'Aloe Barbadensis (Aloe Vera) juice*, Backhousia Citriodora (Lemon Myrtle) extract*, Olea Europaea (Olive Leaf) extract*, Glycerin*, Simmondsia Chinensis (Jojoba) oil*, Cetearyl Olivate, Sorbitan Olivate, Carthamus Tinctorius (Safflower) oil*, Butyrospermum Parki (Shea Butter)*, Garcinia Mangostana (Mangosteen) fruit extract, Triticum Aestivum (Wheatgrass) leaf extract, Camellia Sinensis (Green Tea) leaf extract, Hydrolysed Rice Bran Protein, Euterpe Oleracea (Acai) fruit oil, Persea Gratissima (Avocado) oil, Glyceryl Stearate SE, Pelargonium Roseum (Rose Geranium) leaf oil, Citrus Paradisi (White Grapefruit) peel oil, Tocopherol (Vitamin E), Citric Acid',
    size: '60ml',
    price: 30,
    img: "/images/products/Acai-Bowl-On-My-Face-Day-Cream_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 13,
    name: 'Land of Wonders',
    color: '#5260a9',
    url: 'landOfWonders',
    subName: 'Oil Serum',
    skinType: ['dry'],
    productType: ['serum'],
    description:
    "Our multipurpose Land of Wonders Oil Serum should definitely be a part of every proper skincare routine. This nourishing lightweight oil smells amazing and has so many different uses. Mix a few drops with your moisturiser in the morning for an extra all-day protection and hydration boost or use it as a night treatment to wake up to the most supple, glowing skin.",
    loveList: [
      'Jojoba Oil contains anti-inflammatory compounds and has a molecular structure similar to sebum, which is why this ingredient works so well on all skin types and doesn’t leave a greasy feel',
      'Avocado Oil has great moisturising properties and contains plenty of minerals and vitamins',
      'Chia Seed Oil is a precious source of omega 3 fatty acids which help restore moisture levels and reduce redness',
      'Sea Bucktorns are high in natural vitamins C and E and are used for their nourishing effects in soothing sensitive and easily irritated skin'
    ],
    directions: 'Apply a small amount to the face, neck and décolletage and massage in using gentle upward strokes. For best results apply a moisturiser over the top of your serum. Avoid eye area. Use morning and night.',
    ingredients: 'Prunis Amygdalus Dulcis (Sweet Almond) oil, Simmondsia Chinensis (Jojoba) seed oil, Olea Europaea (Olive) fruit oil*, Hippophae Rhamnoides (Sea Buckthorn berry) kernel extract*, Persea Gratissima (Avocado) oil, Salvia Hispanica (Chia) seed oil, Euterpe Oleracea (Acai) fruit oil, Tocopherol (Vitamin E), Glycine Soja (Soybean) oil, Lavandula Angustifolia oil (Lavender), Boswellia Carterii (Frankincense) oil, Cymbopogon Martini (Palmarosa) oil, Pelargonium Roseum (Rose Geranium) leaf oil, Cananga Odorata flower oil (Ylang Ylang), Anthemis Nobilis (Roman Chamomile) flower oil, Rosmarinus Officinalis (Rosemary) leaf extract*',
    size: '30ml',
    price: 30,
    img: "/images/products/Land-Of-Wonders-Oil-Serum_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 14,
    name: 'Sunny Day in Paradise',
    color: '#d6685b',
    url: 'sunnyDayInParadise',
    subName: 'Brightening Serum',
    skinType: ['dry', 'normal', 'oily'],
    productType: ['serum'],
    description:
    "Perfect for all skin types our Sunny Day in Paradise Brightening Serum is an absolute must-have for everyone, plus it smells divine. It contains six natural, yet very powerful, lightening agents to dramatically improve uneven skin tones. It works by repairing current damage as well as preventing future damage. Amen to bright, natural glowing skin!",
    loveList: [
      'Vegetable Melanin (from the brown fruit of the date palm) protects the skin and has similar properties to our own melanin',
      'Jackfruit is rich in Vitamin A and blocks free radicals to prevent cell degeneration',
      'Probiotic Peptide improves skin tone and reduces the appearance of hyperpigmentation',
      'Mulberry contains vitamin A, C and E which cleanse dead cells, fade dark spots, retain moisture and enhance collagen production',
      'Liquorice helps in the fading of hyper-pigmentation and sun damage for all skin tones in a safe manner',
      'Lemon Peel Ferment is a natural and effective inhibitor of tyrosinase, an enzyme that triggers production of melanin.'
    ],
    directions: 'Apply a small amount to the face, neck and décolletage and massage in using gentle upward strokes. For best results apply a moisturiser over the top of your serum. Avoid eye area. Use morning and night.',
    ingredients: 'Aloe Barbadensis (Aloe Vera) gel*, Aloe Barbadensis (Aloe Vera) extract*, Glycerine*, Artocarpus Heterophyllus (Jackfruit) seed extract, Vegetable Melanin (Date Palm), Lactobacillus Ferment Lysate filtrate (Probiotic Peptide), Morus Alba (White Mulberry) bark extract, Glycyrrhiza Glabra (Liquorice) root extract*, Lemon Peel ferment extract, Pyrus Malus (Apple) fruit extract, Leuconostoc (Radish root) ferment filtrate*',
    size: '30ml',
    price: 30,
    img: "/images/products/Sunny-Day-In-Paradise-Brightening-Serum_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 15,
    name: 'Easy As',
    color: '#bb65a6',
    url: 'easyAs',
    subName: 'Blemish Spot Remover',
    skinType: ['problematic', 'oily'],
    productType: ['treatment'],
    description:
    "Remember that old trick of putting toothpaste on a pimple to make it dry up and disappear more quickly? Well forget it, it doesn’t work, and it can make the situation a lot worse. What does work is our Easy As Blemish Spot Remover, especially formulated with anti-bacterial essential oils and powerful botanical extracts to deeply clean and fight blemishes. This concentrated treatment needs to be applied only on the single problem spots and may cause a slight tingling effect (nothing to worry about, it just means it’s working!).",
    loveList: [
      'Australian Tea Tree and Lemon Myrtle essential oils work together to cleanse and purify the affected area',
      'Salicylic Acid and Papaya Enzyme dissolve bad pimple-causing bacteria to help speed up the healing process and prevent future blemishes',
      'Aloe Vera and reduces redness and swelling'
    ],
    directions: 'Apply a small amount to effected area only. Use morning and night on clean skin. Note: A slight tingling feeling is normal, if stinging occurs remove and discontinue use.',
    ingredients: 'Aloe Barbadensis (Aloe Vera) gel*, Aloe Barbadensis (Aloe Vera) extract*, Glycerin*, Ananas Sativus fruit (Pineapple) extract, Salix Alba (White Willow bark) extract, Glycyrrhiza Glabra (Liquorice) root extract *, Xanthan gum, Citric Acid, Backhousia Citriodora (Lemon Myrtle) oil, Melaleuca Alternifolia (Tea Tree) oil',
    size: '30ml',
    price: 30,
    img: "/images/products/Easy-As-Blemish-Spot-Remover_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 16,
    name: 'Rescue Me',
    color: '#4c6db2',
    url: 'rescueMe',
    subName: 'Acne Lotion',
    skinType: ['problematic'],
    productType: ['moisturiser'],
    description:
    "If you are struggling to find a natural daily moisturiser that won’t be too harsh on your congested skin, then our Rescue Me Acne Lotion will be your best friend. This product is free from any nasties and gentle on the skin but still highly effective against stubborn pimples. It contains Agave Nectar and Lactobacillus, two powerful probiotic ingredients that will help you achieve a healthier and clearer looking skin for a happier and more confident you!",
    loveList: [
      'Blend of light, non-comedogenic, skin loving oils regulate sebum production',
      'Agave Nectar ‘s high sugar content locks in moisture and keeps problem skin hydrated instead of drying and stripping',
      'Lactobacillus provides essential healthy bacteria capable of cleaning up the bad, pimplecausing bacteria which sit on top of the skin'
    ],
    directions: 'Apply a small amount to the face, neck and décolletage and massage in using gentle upward strokes. Avoid eye area. Use morning and night.',
    ingredients: 'Macadamia Integrifolia Seed oil, Prunis Amygdalus Dulcis (Sweet Almond) oil, Helianthus Annuus (Sunflower) seed oil, Rosa Canina (Rose Hip) fruit oil*, Emulsifying Wax, Vegetable Glycerin, Purified Water, Agave Americana Leaf extract, Lactobacillus Bulgaricus Ferment Filtrate, Aloe (Aloe Vera) Barbadensis juice, Salix Alba (White Willow) Bark extract, D-Alpha- Tocopherol (Natural Vitamin E), Rosmarinus Officinalis (Rosemary) extract, Geranium Maculatum extract, Citrus Aurantium Amara (Bitter Orange) flower extract, Gluconolactone (Corn derived), Potassium Sorbate (Salt derived)',
    size: '60ml',
    price: 30,
    img: "/images/products/Rescue-Me-Acne-Lotion_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 17,
    name: 'Summer Fruit Salad',
    color: '#ef4244',
    url: 'summerFruitSalad',
    subName: 'Face Scrub',
    skinType: ['normal' , 'dry'],
    productType: ['exfoliant'],
    description:
    "We are sure it will be love at first try with our gorgeous Summer Fruit Salad Face Scrub. This creamy exfoliant is not harsh on the skin and will leave you feeling super soft and fresh. It contains Rosehip Powder which is an environmental friendly abrasive that thoroughly removes dead skin cells.",
    loveList: [
      'Lemon Myrtle Brightens skin complexion',
      'Watermelon and Davidson Plum keep skin hydrated',
      'Strawberry and Guava Help to shrink and minimise the appearance of pores',
      'No damage to sea life and waterways with our natural rosehip powder'
    ],
    directions: 'Massage a small amount into the face and neck for approximately 1-2 minutes, then rinse off with warm water or face cloth. Use twice a week.',
    ingredients: 'Backhousia Citriodora (Lemon Myrtle) extract*, Olea Europaea (Olive) leaf extract*, Glycerin*, Rosa Canina (Rosehip) seed powder*, Butyrospermum Parkii (Shea Butter)*, Cetearyl Olivate, Sorbitan Olivate, Simmondsia Chinensis (Jojoba) oil*, Carthamus Tinctorius (Safflower) oil*, Glyceryl Stearate, Fragaria Ananassa fruit (Strawberry) extract, Citrullus Lanatus (Watermelon) fruit extract, Psidium Guajava (Guava) fruit extract, Davidsonia Pruriens (Davidson Plum) fruit extract, Sodium Stearate, Lavandula Angustifolia (Lavender) oil, Pogostemon Cablin (Patchouli) oil, Citrus Reticulata (Tangerine) peel oil, Origanum Majorana (Marjoram) leaf oil, Pelargonium Roseum (Geranium) leaf oil, Anthemis Nobilis (Chamomile) flower oil, Citric Acid',
    size: '60ml',
    price: 30,
    img: "/images/products/Summer-Fruit-Salad-Face-Scrub_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  },
  { id: 18,
    name: 'Escape in Bora Bora',
    color: '#0bbff2',
    url: 'escapeInBoraBora',
    subName: 'Body Scrub',
    skinType: ['normal' , 'dry', 'oily', 'sensitive', 'problematic'],
    productType: ['exfoliant'],
    description:
    "Get your skin ready for summer and indulge in our delicious Escape in Bora Bora Body Scrub. This 100% natural sugar and coffee scrub will effectively detoxify your skin and get rid of dull, sad looking cells while the Coconut and Sweet almond oils will nourish and leave your skin feeling silky smooth and energised. Time to show off your glow at the beach!",
    loveList: [
      'Coffee stimulates blood circulation and helps reduce the appearance of cellulite',
      'Sugar removes dead cells and prevents ingrown hair',
      'Scented with uplifting Organic Vanilla Bean',
      'No damage to sea life and waterways with our environmental friendly abrasive ingredients'
    ],
    directions: 'Massage body scrub into damp skin, avoiding face. Rinse off in shower or bath.',
    ingredients: 'Sucrose (Sugar), Coffea Arabica (Coffee), Prunus Amygdalus Dulcis (Sweet Almond) oil, Cocos Nucifera (Coconut) oil*, Sodium Chloride (Sea Salt), Vanilla Planifolia (Vanilla) extract*, Tocopherol (Vitamin E)',
    size: '220g',
    price: 30,
    img: "/images/products/Escape-in-Bora-Bora-Body-Scrub_Just-A-Dash.jpg",
    inCart: false,
    count: 0,
    total:0
  }
]


export const skinTypes = [
  "oily",
  "problematic",
  "sensitive",
  "normal",
  "dry",
  "all"
]

export const prodTypes = [
  "cleanser",
  "toning mist",
  "exfoliant",
  "serum",
  "moisturiser",
  "treatment"
]

export const prodNames = [
  'goodByeSunshine',
  'allUnderControl',
  'lemonCandy',
  'sealTheDeal',
  'thePorefect',
  'coolAsCucumber',
  'quickFix',
  'noHandyMan',
  'greenCocktail',
  'berryFresh',
  'allAboutMoisture',
  'acaiBowl',
  'landOfWonders',
  'sunnyDayInParadise',
  'easyAs',
  'rescueMe',
  'summerFruitSalad',
  'escapeInBoraBora'
]

export const cart = []

  // id,
  // name,
  // url,
  // subName,
  // skinType,
  // productType,
  // description,
  // loveList,
  // directions,
  // ingredients,
  // size,
  // price,
  // img,
  // inCart

  // id, name, url, subName, skinType, productType, description, loveList, directions, ingredients, size, price, img, inCart
